name: Android Build

# 当 push 到特定分支时触发构建
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 JDK 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # 3. 安装 Android SDK
      - name: Set up Android SDK
        uses: reactivecircus/android-sdk-manager-action@v2
        with:
          sdk-version: '30.0.3'

      # 4. 通过 Gradle 构建 APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # 5. 上传构建的 APK 文件
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
