name: Android Build with Gradle Upgrade

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 JDK 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. 升级 Gradle Wrapper 到指定版本
      - name: Upgrade Gradle Wrapper
        run: |
          ./gradlew wrapper --gradle-version 7.6 --distribution-type all
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.jar
          git commit -m "Upgrade Gradle Wrapper to 7.6" || echo "No changes to commit"
          git push || echo "No changes to push"

      # 4. 验证 Gradle Wrapper 版本
      - name: Verify Gradle Wrapper version
        run: ./gradlew --version

      # 5. 设置 Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30.0.3'

      # 6. 通过 Gradle 构建 APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # 7. 上传构建的 APK 文件
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
